use_frameworks!

platform :ios, '9.0'

target 'AAA_Example' do
#  pod 'AAA', :path => '../'

   pod 'AAA', :podspec => '../AAA.podspec'

  target 'AAA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
